# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres:9.6
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=pwd
        - POSTGRES_DB=sqlalchemy
#      - PGDATA=/var/lib/postgresql/data/pgdata
#     volumes:
#         - ./data/postgres:/var/lib/postgresql/data 
    ports:
      - "54322:5432"